--Dropping all tables and objects from Lily Landscaping Database

DROP TABLE PURCHASED;
DROP TABLE RENTED;
DROP TABLE INITIAL_RENOVATION;
DROP TABLE MAINTENANCE;
DROP TABLE USAGE_LOG;
DROP TABLE EQUIPMENT;
DROP TABLE TOOL;
DROP TABLE VEHICLE;
DROP TABLE TIME_ENTRY;
DROP TABLE LABOR_RATE;
DROP TABLE PAY_STATEMENT;
DROP TABLE EMPLOYEE;
DROP TABLE PRICE;
DROP TABLE SUPPLIER;
DROP TABLE BID;
DROP TABLE CONTRACT;
DROP TABLE CLIENT;